[package]
name = "hallo"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]
edition = "2018"

[[bin]]
name = "hallo"
path = "./hallo/src/main.rs"

[lib]
name = "hallo"
crate-type = ["cdylib"]
path = "./hallo/src/lib.rs"